version: '3.8'

services:
  v-master:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - HOST=0.0.0.0
      - PORT=3003
    restart: unless-stopped
    command: npm run dev